# HW01 (제출기한-3월31일23시)
NumPy 이해도 평가를 위한 문제입니다. 
- Loop를 사용하면 감점입니다.
- Random을 다양하게 사용하여 테스트합니다.

제출시 다음 사항에 유의하기 바랍니다.
- 텍스트 셀에 설명되어 있는 각 문항을 잘 읽은 뒤,
- 코드 셀에 적절한 코드를 작성하기 바랍니다.
- 작성 후 파일명에 ``학번``을 명시후 지정한 공유폴더에 업로드합니다.
- 이때, 공유를 반드시 profkwon@cicweb.ulsan.ac.kr 에게만 합니다.


In [ ]:
import numpy as np
rng=np.random.RandomState(100)

### 문제1
0이상 100이하 정수들로 구성되는 100행 5열의 2차원 array인 ``score``를 생성하시오.
(단, 위 rng를 사용할 것)

In [ ]:
score=rng.randint(100,size=(100,5))
score

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98],
       [53, 66, 98, 14, 34],
       [24, 15, 60, 58, 16],
       [ 9, 93, 86,  2, 27],
       [ 4, 31,  1, 13, 83],
       [ 4, 91, 59, 67,  7],
       [49, 47, 65, 61, 14],
       [55, 71, 80,  2, 94],
       [19, 98, 63, 53, 27],
       [56, 30, 48, 47, 39],
       [38, 44, 18, 64, 56],
       [34, 53, 74, 17, 72],
       [13, 30, 17, 53, 68],
       [50, 91, 91, 83, 53],
       [78,  0, 13, 57, 76],
       [ 3, 70,  3, 84, 79],
       [10, 87, 60,  3, 48],
       [52, 43, 36,  5, 71],
       [38, 86, 94, 98, 42],
       [84, 95, 76, 33, 58],
       [42, 22,  0, 55, 98],
       [19, 53, 68, 62, 50],
       [68, 35, 23,  9, 48],
       [21, 25, 54,  6, 37],
       [58, 39, 94, 51, 30],
       [66, 24, 55, 17, 45],
       [89, 45, 35, 16, 12],
       [86, 82, 67, 92, 95],
       [20, 10,  8, 89, 72],
       [30, 12, 18, 93, 92],
       [44, 57,  0, 73, 54],
       [92, 66, 16,  5, 51],
       [90, 34, 67, 94, 78],
       [54, 77

### 문제2
지금부터 ``score``가 100명의 학생들의 국어, 영어, 수학, 과학, 사회 점수를 뜻한다고 가정하자.

이제 5개 과목의 평균점수를 뜻하는 ``avgx`` array(1차원)를 생성하시오. 

In [ ]:
avgx_array=score.mean(axis=0)
avgx_array

array([51.53, 50.35, 45.53, 52.45, 52.93])

### 문제3
학생별 평균점수를 뜻하는 ``avgy`` array(1차원)를 생성하시오. 

In [ ]:
avgy_array=score.mean(axis=1)
avgy_array

array([53. , 60.4, 53. , 34.6, 43.4, 26.4, 45.6, 47.2, 60.4, 52. , 44. ,
       44. , 50. , 36.2, 73.6, 44.8, 47.8, 41.6, 41.4, 71.6, 69.2, 43.4,
       50.4, 36.6, 28.6, 54.4, 41.4, 39.4, 84.4, 39.8, 49. , 45.6, 46. ,
       72.6, 46. , 42. , 51.4, 49.6, 74. , 43. , 40.6, 31. , 54.4, 45. ,
       51.6, 55.6, 68.4, 63.6, 49.8, 30. , 50.2, 55.4, 75. , 46.4, 49. ,
       53.6, 32.6, 61.4, 58.4, 48. , 47. , 44.6, 56. , 35.2, 46.2, 29.8,
       65.6, 28.4, 39.6, 62.6, 38. , 61.8, 53.6, 64.6, 46.6, 60. , 38.6,
       67.4, 75.4, 44.2, 24.4, 60.4, 60.8, 23.2, 53.4, 61. , 59.6, 41.2,
       61.8, 58.6, 55.4, 38.2, 54.4, 62.8, 49.6, 57.4, 72. , 55.8, 55.2,
       47.6])

### 문제4
100명 중 홀수번째는 여학생, 짝수번째는 남학생 정보를 뜻한다.

여학생 전체의 5개과목별 평균점수를 뜻하는 ``avgx1`` array(1차원)을 구하시오.

In [ ]:
avgx1_array=score[0::2].mean(axis=0)
avgx1_array

array([52.52, 57.74, 50.52, 51.84, 50.96])

### 문제5
마찬가지로 남학생 전체의 5개과목별 평균점수를 뜻하는 ``avgx2`` array(1차원)을 구하시오.

In [ ]:
avgx2_array=score[1::2].mean(axis=0)
avgx2_array

array([50.54, 42.96, 40.54, 53.06, 54.9 ])

### 문제6

$\frac{avgx1+avgx2}{2}$ 결과를 출력하시오. (변수에 저장할 필요 없음)

(그리고 출력된 array가 ``avgx1``과 같은지 확인)

In [ ]:
(avgx1_array+avgx2_array)/2

array([51.53, 50.35, 45.53, 52.45, 52.93])

### 문제7
각 점수가 해당과목 평균으로부터 얼마나 차이가 나는지를 나타내는 ``score_dev`` array(2차원)를 생성하시오.
- 즉, score_dev의 shape는 score의 shape와 동일하다.
- 점수가 30점이고 평균이 45점이면 그 차이는 $30-45=-15$ 점이다.


In [ ]:
score_dev_array=score-avgx_array
score_dev_array

array([[-43.53, -26.35,  21.47,  34.55,  26.07],
       [ -3.53, -40.35,  48.47,  -0.45,  45.07],
       [  1.47,  15.65,  52.47, -38.45, -18.93],
       [-27.53, -35.35,  14.47,   5.55, -36.93],
       [-42.53,  42.65,  40.47, -50.45, -25.93],
       [-47.53, -19.35, -44.53, -39.45,  30.07],
       [-47.53,  40.65,  13.47,  14.55, -45.93],
       [ -2.53,  -3.35,  19.47,   8.55, -38.93],
       [  3.47,  20.65,  34.47, -50.45,  41.07],
       [-32.53,  47.65,  17.47,   0.55, -25.93],
       [  4.47, -20.35,   2.47,  -5.45, -13.93],
       [-13.53,  -6.35, -27.53,  11.55,   3.07],
       [-17.53,   2.65,  28.47, -35.45,  19.07],
       [-38.53, -20.35, -28.53,   0.55,  15.07],
       [ -1.53,  40.65,  45.47,  30.55,   0.07],
       [ 26.47, -50.35, -32.53,   4.55,  23.07],
       [-48.53,  19.65, -42.53,  31.55,  26.07],
       [-41.53,  36.65,  14.47, -49.45,  -4.93],
       [  0.47,  -7.35,  -9.53, -47.45,  18.07],
       [-13.53,  35.65,  48.47,  45.55, -10.93],
       [ 32.47,  44.

### 문제8
``score``에서 ``avgx``를 계산하였듯이 ``score_dev``에서 axis=0 방향으로 평균을 나타내는 ``scorex_dev``를 구하시오. 

In [ ]:
scorex_dev=score_dev_array.mean(axis=0)
scorex_dev

array([ 8.52651283e-15,  1.27897692e-15, -8.52651283e-16,  5.96855898e-15,
       -2.48689958e-15])

### 문제9
전체과목 평균을 기준으로 1등을 한 학생의 5개 과목 점수를 출력하시오. (1차원 array 형태로 출력하면 됨) 

In [ ]:
winner=score[avgy_array==avgy_array.max()]
winner

array([[86, 82, 67, 92, 95]])

### 문제10
모든 과목이 각 과목의 평균점수보다 높은 학생수를 구하시오. 

In [ ]:
member=np.sum(np.sum(score_dev_array>0,axis=1)==5,axis=0)
member

2

### 보너스문제
위 데이터에 대하여 본인이 출제하고 싶은 문제가 있으면 한 문제를 출제하고 아래에 답안 코드를 작성하시오.

모든 과목을 고르게 공부하여 가장 성적이 고르게 나온 학생을 구하시오.(표준편차를 이용)



In [ ]:
goodstudent=score[score.std(axis=1)==score.std(axis=1).min()]
goodstudent

array([[56, 30, 48, 47, 39]])