# Computation on Arrays: Broadcasting

또 다른 *vectorize* operation의 예는 NumPy *broadcasting* 기능을 이용하는 것이다.
Broadcasting 은 서로 다른 크기의 array의 연산이 가능하도록 하는 다음 몇 가지 규칙을 말한다. 

## Rules of Broadcasting

임의의 두 array에 대해 다음과 같은 규칙이 적용된다. 

- Rule 1: 두 array의 차원 수가 다를 경우 낮은 차원 수의 array에서 부족한 차원 개수만큼 왼쪽에 1을 집어넣어 차원수를 맞춘다. 
- Rule 2: 각 차원에서 그 크기가 다른 경우 차원값이 1인 것을 변경하여 일치시킨다. 
- Rule 3: Rule 2가 적용되지 않는다면 오류를 발생시킨다. 

In [0]:
import numpy as np

### Broadcasting example 1


In [8]:
M = np.ones((2, 3))
a = np.arange(3)
print(M)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


두 array의 shape는 다음과 같다. 

- ``M.shape = (2, 3)``
- ``a.shape = (3,)``

Rule 1에 의해, 

- ``M.shape -> (2, 3)``
- ``a.shape -> (1, 3)``

Rule 2에 의해, 

- ``M.shape -> (2, 3)``
- ``a.shape -> (2, 3)``

따라서 다음과 같이 계산된다. 

In [9]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

### Broadcasting example 2


In [0]:
a = np.arange(3).reshape((3, 1))
b = np.arange(3)

두 array의 shape는 다음과 같다.

- ``a.shape = (3, 1)``
- ``b.shape = (3,)``

Rule 1 에 의해,

- ``a.shape -> (3, 1)``
- ``b.shape -> (1, 3)``

Rule 2 에 의해,

- ``a.shape -> (3, 3)``
- ``b.shape -> (3, 3)``

따라서 다음과 같이 계산된다.

In [5]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Broadcasting example 3


In [0]:
M = np.ones((3, 2))
a = np.arange(3)

두 array의 shape는 다음과 같다.

- ``M.shape = (3, 2)``
- ``a.shape = (3,)``

Rule 1 에 의해,

- ``M.shape -> (3, 2)``
- ``a.shape -> (1, 3)``

Rule 2 에 의해,

- ``M.shape -> (3, 2)``
- ``a.shape -> (3, 3)``

Rule 3 에 의해 오류가 발생한다.

In [7]:
M + a

ValueError: ignored

## Broadcasting in Practice

### Centering an array

In [12]:
X = np.random.random((10, 3))
X

array([[0.15032548, 0.89952053, 0.80193267],
       [0.88594274, 0.54307253, 0.3234129 ],
       [0.55821018, 0.2314001 , 0.80667795],
       [0.388321  , 0.18428195, 0.76294774],
       [0.88555515, 0.09735332, 0.89458388],
       [0.54777102, 0.14937318, 0.75702769],
       [0.51483914, 0.23470288, 0.24642148],
       [0.17171421, 0.5477513 , 0.87072288],
       [0.72219954, 0.85703227, 0.04012161],
       [0.22280159, 0.68384696, 0.60964029]])

In [13]:
Xmean = X.mean(0)
Xmean

array([0.504768  , 0.4428335 , 0.61134891])

In [0]:
X_centered = X - Xmean

``X_centered``의 shape와 결과를 생각해 보자.